
//////////////////////////////////////////////////////////////////
// auto generated by DapperHelper, DON'T modify it
//////////////////////////////////////////////////////////////////

using System;

namespace IQF.BizCommon.User.Entity
{
	public partial class VerifyCodeInfoEntity
	{
		/// <summary>
		/// 
		/// </summary>
		public long VerifyCodeID { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string Mobile { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string VerifyCode { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public int VerifyCodeType { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public int Status { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string Comment { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public int PackType { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public DateTime AddTime { get; set; }
	} //end of class
} //end of namespace
