
//////////////////////////////////////////////////////////////////
// auto generated by DapperHelper, DON'T modify it
//////////////////////////////////////////////////////////////////

using System;

namespace IQF.BizCommon.Data.Entity
{
    internal partial class ContractEntity
    {
        /// <summary>
        /// 合约ID
        /// </summary>
        public long ContractID { get; set; }
        /// <summary>
        /// 品种Id
        /// </summary>
        public long VarietyID { get; set; }
        /// <summary>
        /// 合约代码
        /// </summary>
        public string Code { get; set; }
        /// <summary>
        /// 合约名称
        /// </summary>
        public string ContractName { get; set; }
        /// <summary>
        /// 交易所
        /// </summary>
        public int Exchange { get; set; }
        /// <summary>
        ///上市日期
        /// </summary>
        public DateTime OpenDate { get; set; }
        /// <summary>
        /// 到期日
        /// </summary>
        public DateTime ExpireDate { get; set; }
        /// <summary>
        /// 开始交割日期
        /// </summary>
        public DateTime StartDeliverDate { get; set; }
        /// <summary>
        /// 最后交割日期
        /// </summary>
        public DateTime EndDeliverDate { get; set; }
        /// <summary>
        /// 添加时间
        /// </summary>
        public DateTime AddTime { get; set; }
        /// <summary>
        /// 编辑时间
        /// </summary>
        public DateTime EditTime { get; set; }
    }
}
