
//////////////////////////////////////////////////////////////////
// auto generated by DapperHelper, DON'T modify it
//////////////////////////////////////////////////////////////////

using System;

namespace IQF.BizCommon.Data.Entity
{
	 partial class HolidaysDateEntity
    {
        /// <summary>
        /// 
        /// </summary>
        public DateTime Date { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string HolidayName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int Type { get; set; }
    } //end of class
} //end of namespace
