
//////////////////////////////////////////////////////////////////
// auto generated by DapperHelper, DON'T modify it
//////////////////////////////////////////////////////////////////

using System;

namespace IQF.BizCommon.Data.Entity
{
	internal partial class VarietyEntity
    {
		/// <summary>
		/// 
		/// </summary>
		public long ID { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public int EID { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string VarietyCode { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string VarietyName { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public int Type { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string NewsName { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public int State { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public int Lots { get; set; }
		/// <summary>
		/// 最小变动价位
		/// </summary>
		public decimal PriceStep { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public DateTime AddTime { get; set; }
	} //end of class
} //end of namespace
