
//////////////////////////////////////////////////////////////////
// auto generated by DapperHelper, DON'T modify it
//////////////////////////////////////////////////////////////////

using System;

namespace IQF.BizCommon.Data.Entity
{
	internal partial class VarietyIndustryEntity
    {
		/// <summary>
		/// 
		/// </summary>
		public int Id { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public int IndCatgID { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public int VerietyID { get; set; }
	} //end of class
} //end of namespace
