
//////////////////////////////////////////////////////////////////
// auto generated by DapperHelper, DON'T modify it
//////////////////////////////////////////////////////////////////

using System;

namespace IQF.BizCommon.Data.Entity
{
	internal partial class VarietyOpenTimeEntity
    {
		/// <summary>
		/// 
		/// </summary>
		public long ID { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public long VID { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string VarietyCode { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string BeginTime { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string EndTime { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public DateTime UpdateTime { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public DateTime AddTime { get; set; }
	} //end of class
} //end of namespace
