
//////////////////////////////////////////////////////////////////
// auto generated by DapperHelper, DON'T modify it
//////////////////////////////////////////////////////////////////

using System;

namespace IQF.BizCommon.Data.Entity
{
	public partial class VirtualVariety
	{
		/// <summary>
		/// 
		/// </summary>
		public long VarietyID { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string VarietyName { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public DateTime AddTime { get; set; }
	} //end of class
} //end of namespace
